In [23]:
import torch
import numpy as np

In [3]:
# in pytorch, everything runs based on tensor
t1=torch.empty(2,3)
t1

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.1046e-43]])

In [6]:
t2=torch.rand(2,2)
t2

tensor([[0.4945, 0.8624],
        [0.5757, 0.7962]])

In [8]:
torch.ones(2,2,dtype=torch.int)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [11]:
# create tensor from a list
t3=torch.tensor([[3,2],[2,1]],dtype=torch.float64)
t3

tensor([[3., 2.],
        [2., 1.]], dtype=torch.float64)

In [12]:
# arithmatic operations
torch.add(t2,t3)

tensor([[3.4945, 2.8624],
        [2.5757, 1.7962]], dtype=torch.float64)

In [13]:
# underscore means in-place
t2.add_(t3)

tensor([[3.4945, 2.8624],
        [2.5757, 1.7962]])

In [17]:
# get the value
t2[0,0].item()

3.4944567680358887

In [19]:
#reshape the tensor
t4=torch.rand(4,4)
t4.view(-1,8).shape

torch.Size([2, 8])

### convert from numpy to tensor and vice versa

In [22]:
type(t4.numpy())

numpy.ndarray

In [24]:
n1=np.ones([3,3])
torch.from_numpy(n1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [26]:
# note that on GPU, tensor and numpy share same memory, changing value on np will change value on tensor as well.
# tensors on CPU and Cuda can be different!

In [28]:
# requires_grad arg tells torch that this is a variable, and will be used for back-prop in gradient descent.
t5=torch.ones(4,4,requires_grad=True)