In [1]:
import torch

In [30]:
# calculate the gradient
x=torch.tensor([[2.1,3],[1.4,4]],requires_grad=True)
x

tensor([[2.1000, 3.0000],
        [1.4000, 4.0000]], requires_grad=True)

In [31]:
y=x*x+3+2*x
y

tensor([[11.6100, 18.0000],
        [ 7.7600, 27.0000]], grad_fn=<AddBackward0>)

In [32]:
z=y.mean()
z

tensor(16.0925, grad_fn=<MeanBackward0>)

In [19]:
z.backward()

In [20]:
x.grad

tensor([[1.5500, 2.0000],
        [1.2000, 2.5000]])

In [25]:
# if y is not scalar, then we need to pass the argument of a tensor that has same shape with y
y.backward(torch.tensor([[1,1],[1,1]]))

In [28]:
# we can get a copy of a tensor without gradients using tensor.detach() method.
y.detach()

tensor([[11.6100, 18.0000],
        [ 7.7600, 27.0000]])

In [34]:
# note that in pytorch, the grad will accumulate when we apply backward multiple times.
weight=torch.ones(4,requires_grad=True)
for i in range(3):
    model_output=(weight*3).sum()
    model_output.backward()
    print(weight.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [35]:
# always use tensor.grad.zero_() to clean previous grad values
weight=torch.ones(4,requires_grad=True)
for i in range(3):
    model_output=(weight*3).sum()
    model_output.backward()
    print(weight.grad)
    weight.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
